### ISSUE TITLE
Work in tandem with another google api library 

### ISSUE THREAD

**Issue by llermaly** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#1060]
## Question

We have 2 Logstash instances, one that has [gcp_pubsub input plugin](https://github.com/logstash-plugins/logstash-input-google_pubsub), and another one that uses this socked-factory

Both instances work separately, but when I try to use both things in one instance it fails.

This is the error:

```
java.lang.NoClassDefFoundError: org/threeten/bp/Duration\n\tat com.google.api.gax.retrying.RetrySettings.newBuilder(com/google/api/gax/retrying/RetrySettings.java:146) ~[postgres-socket-factory-1.6.4-SNAPSHOT-jar-with-dependencies.jar:?]\n\tat com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.<clinit>(com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java:560) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.stub.SubscriberStubSettings.newBuilder(com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java:453) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber.<init>(com/google/cloud/pubsub/v1/Subscriber.java:189) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber.<init>(com/google/cloud/pubsub/v1/Subscriber.java:91) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber$Builder.build(com/google/cloud/pubsub/v1/Subscriber.java:707) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]\n\tat jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77) ~[?:?]\n\tat jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43) ~[?:?]\n\tat java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568) ~[?:?]\n\tat org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:442) ~[jruby.jar:?]\n\tat org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:306) ~[jruby.jar:?]\n\tat RUBY.run(/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-google_pubsub-1.2.2/lib/logstash/inputs/google_pubsub.rb:274) ~[?:?]\n\tat RUBY.inputworker(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:411) ~[?:?]\n\tat RUBY.start_input(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:402) ~[?:?]\n\tat org.jruby.RubyProc.call(org/jruby/RubyProc.java:309) ~[jruby.jar:?]\n\tat java.lang.Thread.run(java/lang/Thread.java:833) [?:?]\nCaused by: java.lang.ClassNotFoundException: org.threeten.bp.Duration\n\tat jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]\n\tat jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]\n\tat com.google.api.gax.retrying.RetrySettings.newBuilder(RetrySettings.java:146) ~[postgres-socket-factory-1.6.4-SNAPSHOT-jar-with-dependencies.jar:?]\n\tat com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.<clinit>(SubscriberStubSettings.java:560) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.stub.SubscriberStubSettings.newBuilder(SubscriberStubSettings.java:453) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber.<init>(Subscriber.java:189) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber.<init>(Subscriber.java:91) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat com.google.cloud.pubsub.v1.Subscriber$Builder.build(Subscriber.java:707) ~[google-cloud-pubsub-1.120.13.jar:1.120.13]\n\tat jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]\n\tat jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]\n\tat jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]\n\tat java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]\n\tat org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:442) ~[jruby.jar:?]\n\tat org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:306) ~[jruby.jar:?]\n\tat org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:32) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:351) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:144) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:201) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:188) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:372) ~[jruby.jar:?]\n\tat org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:175) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72) ~[jruby.jar:?]\n\tat org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116) ~[jruby.jar:?]\n\tat org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136) ~[jruby.jar:?]\n\tat org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66) ~[jruby.jar:?]\n\tat org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58) ~[jruby.jar:?]\n\tat org.jruby.runtime.Block.call(Block.java:143) ~[jruby.jar:?]\n\tat org.jruby.RubyProc.call(RubyProc.java:309) ~[jruby.jar:?]\n\tat org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:107) ~[jruby.jar:?]\n\tat java.lang.Thread.run(Thread.java:833) ~[?:?]
```

## Additional Context

I just discovered that the socket factory include some exclusions, one of them threeten. If I remove it then the error changes and complains for a different one (google api core NanoClock). If I remove all the exclusions building fails.

```
 <dependency>
      <groupId>com.google.api</groupId>
      <artifactId>gax</artifactId>
      <version>2.19.5</version>
      <exclusions>
        <!-- Native image users only need GAX's native-image metadata. GAX's
        dependencies are unnecessary for normal users and native image users -->
        <exclusion>
          <groupId>com.google.api</groupId>
          <artifactId>api-common</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.auth</groupId>
          <artifactId>google-auth-library-credentials</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.auth</groupId>
          <artifactId>google-auth-library-oauth2-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.code.findbugs</groupId>
          <artifactId>jsr305</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.protobuf</groupId>
          <artifactId>protobuf-java</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.opencensus</groupId>
          <artifactId>opencensus-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.threeten</groupId>
          <artifactId>threetenbp</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

How can I make both libraries work together?

**Comment by llermaly** [comment]
I just deleted the exclusions and saw this error: 

```
[WARNING]
Dependency convergence error for com.google.auth:google-auth-library-credentials:jar:1.13.0:compile paths to dependency are:
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.auth:google-auth-library-oauth2-http:jar:1.13.0:compile
    +-com.google.auth:google-auth-library-credentials:jar:1.13.0:compile
and
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.api:gax:jar:2.19.5:compile
    +-com.google.auth:google-auth-library-credentials:jar:1.12.1:compile

[WARNING]
Dependency convergence error for com.google.auth:google-auth-library-oauth2-http:jar:1.13.0:compile paths to dependency are:
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.auth:google-auth-library-oauth2-http:jar:1.13.0:compile
and
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.api:gax:jar:2.19.5:compile
    +-com.google.auth:google-auth-library-oauth2-http:jar:1.12.1:runtime

[WARNING]
Dependency convergence error for io.opencensus:opencensus-api:jar:0.31.1:compile paths to dependency are:
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.http-client:google-http-client:jar:1.42.3:compile
    +-io.opencensus:opencensus-api:jar:0.31.1:compile
and
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.http-client:google-http-client:jar:1.42.3:compile
    +-io.opencensus:opencensus-contrib-http-util:jar:0.31.1:compile
      +-io.opencensus:opencensus-api:jar:0.31.1:compile
and
+-com.google.cloud.sql:jdbc-socket-factory-core:jar:1.7.3-SNAPSHOT
  +-com.google.api:gax:jar:2.19.5:compile
    +-io.opencensus:opencensus-api:jar:0.28.0:runtime

[ERROR] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
```

Then disabled the enforcer and now it works. I'm not a Java expert so I'm not sure on how safe is to do this.

**Comment by shubha-rajan** [comment]
Thanks for opening this issue! 

Generally, we don't recommend disabling the enforcer as this could lead to errors from missing classes etc. Instead, you'll probably want to use the `dependencyManagement` section of the `pom.xml` file to set the desired version for each of the dependency conflicts. 

We'll look into removing the exclusions and using dependency management instead, since errors when using other Google API libraries are not the intended behavior.

**Comment by vr** [comment]
Hello here, 
i think maybe metabase got same kind of issues when adding cloud-sql-jdbc-socket-factory concurrently with bigquery lib https://github.com/metabase/metabase/issues/23895
Do you confirm it can be related ?

/cc https://github.com/metabase/metabase/issues/27117

**Comment by enocom** [comment]
Closing this as stale. Feel free to re-open with additional information if necessary.
