### ISSUE TITLE
Add support for mysql-connector-j8

### ISSUE THREAD

**Issue by jeffyecn** [GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#73]
Go this error: java.lang.NoClassDefFoundError: com/mysql/cj/api/io/SocketFactory

Seems like the SocketFactory interface changed to com.mysql.cj.protocol.SocketFactory

**Comment by kurtisvg** [comment]
Hi @jeffyecn - Are you using this to connect to a Cloud SQL instance? My understanding is that the 8.x connectors are for MySQL 8.x. Cloud SQL doesn't have any 8.x offerings at this time.

**Comment by jeffyecn** [comment]
@kurtisvg Thanks for you reply. I assume it is compatible with previous mysql server version as well. It is working on version 8.0.8. I think just the socket factory interface has been changed make it not working now. But the driver itself should working good with the google cloud sql server. Since our project is using connector-8 for connecting other db, it is much easier for the socket-factory can support connector-8 as well, so we do not need to work around to mysql-connector version in a project.
